from base64 import b64decode

import pytest

from scallop.cli import _sanitize_output_name
from scallop.sea import (
    NODE_SEA_MAGIC,
    SeaBinary,
    SeaBlobFlags,
    SeaBlobLayout,
    SeaExecArgvExtension,
    SeaMainCodeFormat,
    deserialize_sea_blob,
    serialize_sea_blob,
)


MACHINE_WIDTH = 8
# Generated by Node 24.19.0 and Node 26.8.1 respectively from the same small
# main/asset/execArgv configuration. Keeping the exact bytes catches accidental
# agreement between Scallop's serializer and deserializer.
NODE_24_19_BLOB = b64decode(
    "INpDARkAAAACBwAAAAAAAABtYWluLmpzWAAAAAAAAABjb25zdCB7IGdldEFzc2V0IH0g"
    "PSByZXF1aXJlKCJub2RlOnNlYSIpOwpjb25zb2xlLmxvZyhnZXRBc3NldCgiZml4dHVy"
    "ZS50eHQiLCAidXRmOCIpKTsKAQAAAAAAAAALAAAAAAAAAGZpeHR1cmUudHh0DgAAAAAA"
    "AABub2RlLTI0LWFzc2V0CgIAAAAAAAAADQAAAAAAAAAtLW5vLXdhcm5pbmdzCwAAAAAA"
    "AAAtLWV4cG9zZS1nYw=="
)
NODE_26_8_BLOB = b64decode(
    "INpDARkAAAACAQgAAAAAAAAAbWFpbi5tanNTAAAAAAAAAGltcG9ydCB7IGdldEFzc2V0"
    "IH0gZnJvbSAibm9kZTpzZWEiOwpjb25zb2xlLmxvZyhnZXRBc3NldCgiZml4dHVyZS50"
    "eHQiLCAidXRmOCIpKTsKAQAAAAAAAAALAAAAAAAAAGZpeHR1cmUudHh0DgAAAAAAAABu"
    "b2RlLTI2LWFzc2V0CgEAAAAAAAAADQAAAAAAAAAtLW5vLXdhcm5pbmdz"
)


def _uint(value: int, size: int = MACHINE_WIDTH) -> bytes:
    return value.to_bytes(size, "little")


def _view(value: bytes) -> bytes:
    return _uint(len(value)) + value


def _legacy_blob(flags: SeaBlobFlags = SeaBlobFlags.DEFAULT) -> bytes:
    return (
        NODE_SEA_MAGIC
        + _uint(int(flags), 4)
        + _view(b"legacy.js")
        + _view(b"console.log('legacy')")
    )


def _exec_argv_blob() -> bytes:
    flags = (
        SeaBlobFlags.DISABLE_EXPERIMENTAL_SEA_WARNING
        | SeaBlobFlags.INCLUDE_ASSETS
        | SeaBlobFlags.INCLUDE_EXEC_ARGV
    )
    return (
        NODE_SEA_MAGIC
        + _uint(int(flags), 4)
        + _uint(SeaExecArgvExtension.CLI, 1)
        + _view(b"sea-loader.js")
        + _view(b"console.log('copilot-like')")
        + _uint(1)
        + _view(b"copilot.tgz")
        + _view(b"\x1f\x8bfixture")
        + _uint(2)
        + _view(b"--no-warnings")
        + _view(b"--expose-gc")
    )


def _main_format_blob() -> bytes:
    flags = SeaBlobFlags.INCLUDE_ASSETS
    return (
        NODE_SEA_MAGIC
        + _uint(int(flags), 4)
        + _uint(SeaExecArgvExtension.ENV, 1)
        + _uint(SeaMainCodeFormat.MODULE, 1)
        + _view(b"main.mjs")
        + _view(b"export default 42")
        + _uint(1)
        + _view("café.txt".encode())
        + _view(b"asset")
    )


@pytest.mark.parametrize(
    ("raw", "layout"),
    [
        (_legacy_blob(), SeaBlobLayout.LEGACY),
        (_exec_argv_blob(), SeaBlobLayout.EXEC_ARGV),
        (_main_format_blob(), SeaBlobLayout.MAIN_CODE_FORMAT),
    ],
    ids=("legacy", "exec-argv", "main-code-format"),
)
def test_detects_and_round_trips_known_layouts(raw, layout):
    blob = deserialize_sea_blob(raw, MACHINE_WIDTH)

    assert blob.layout == layout
    assert serialize_sea_blob(blob) == raw


def test_parses_node_24_exec_argv_and_assets():
    blob = deserialize_sea_blob(_exec_argv_blob(), MACHINE_WIDTH)

    assert blob.exec_argv_extension == SeaExecArgvExtension.CLI
    assert blob.code_path == "sea-loader.js"
    assert blob.assets == {"copilot.tgz": b"\x1f\x8bfixture"}
    assert blob.exec_argv == ["--no-warnings", "--expose-gc"]


def test_parses_node_26_main_code_format():
    blob = deserialize_sea_blob(_main_format_blob(), MACHINE_WIDTH)

    assert blob.main_code_format == SeaMainCodeFormat.MODULE
    assert blob.assets == {"café.txt": b"asset"}


@pytest.mark.parametrize(
    ("raw", "layout", "main_format"),
    [
        (NODE_24_19_BLOB, SeaBlobLayout.EXEC_ARGV, None),
        (
            NODE_26_8_BLOB,
            SeaBlobLayout.MAIN_CODE_FORMAT,
            SeaMainCodeFormat.MODULE,
        ),
    ],
    ids=("node-24.19", "node-26.8"),
)
def test_real_node_generated_blob(raw, layout, main_format):
    blob = deserialize_sea_blob(raw, MACHINE_WIDTH)

    assert blob.layout == layout
    assert blob.main_code_format == main_format
    assert blob.assets["fixture.txt"].endswith(b"-asset\n")
    assert serialize_sea_blob(blob) == raw


def test_snapshot_flag_does_not_imply_code_cache():
    raw = _legacy_blob(SeaBlobFlags.USE_SNAPSHOT)

    blob = deserialize_sea_blob(raw, MACHINE_WIDTH)

    assert blob.code_cache is None
    assert serialize_sea_blob(blob) == raw


def test_parses_32_bit_size_fields():
    code_path = b"main.js"
    resource = b"source"
    raw = (
        NODE_SEA_MAGIC
        + _uint(0, 4)
        + _uint(len(code_path), 4)
        + code_path
        + _uint(len(resource), 4)
        + resource
    )

    blob = deserialize_sea_blob(raw, 4)

    assert blob.machine_width == 4
    assert blob.code_path == "main.js"
    assert serialize_sea_blob(blob) == raw


@pytest.mark.parametrize("cut", [0, 1, 4, 8, 9, 16, 32])
def test_rejects_truncated_blob(cut):
    raw = _exec_argv_blob()

    with pytest.raises(ValueError):
        deserialize_sea_blob(raw[:cut], MACHINE_WIDTH)


def test_rejects_truncated_payload():
    raw = _exec_argv_blob()

    with pytest.raises(ValueError, match="Truncated|exceeds|cannot fit"):
        deserialize_sea_blob(
            raw[:-1], MACHINE_WIDTH, SeaBlobLayout.EXEC_ARGV
        )


def test_rejects_trailing_data():
    with pytest.raises(ValueError, match="trailing"):
        deserialize_sea_blob(
            _legacy_blob() + b"unexpected",
            MACHINE_WIDTH,
            SeaBlobLayout.LEGACY,
        )


def test_rejects_invalid_utf8():
    raw = (
        NODE_SEA_MAGIC
        + _uint(0, 4)
        + _view(b"\xff.js")
        + _view(b"source")
    )

    with pytest.raises(ValueError, match="valid UTF-8"):
        deserialize_sea_blob(raw, MACHINE_WIDTH, SeaBlobLayout.LEGACY)


def test_rejects_impossible_asset_count():
    raw = (
        NODE_SEA_MAGIC
        + _uint(int(SeaBlobFlags.INCLUDE_ASSETS), 4)
        + _view(b"main.js")
        + _view(b"source")
        + _uint(2**63)
    )

    with pytest.raises(ValueError, match="cannot fit"):
        deserialize_sea_blob(raw, MACHINE_WIDTH, SeaBlobLayout.LEGACY)


def test_rejects_duplicate_asset_names():
    raw = (
        NODE_SEA_MAGIC
        + _uint(int(SeaBlobFlags.INCLUDE_ASSETS), 4)
        + _view(b"main.js")
        + _view(b"source")
        + _uint(2)
        + _view(b"same")
        + _view(b"one")
        + _view(b"same")
        + _view(b"two")
    )

    with pytest.raises(ValueError, match="Duplicate"):
        deserialize_sea_blob(raw, MACHINE_WIDTH, SeaBlobLayout.LEGACY)


def test_elf_note_parser_honors_descriptor_size():
    def note(name: bytes, descriptor: bytes) -> bytes:
        name = name + b"\x00"
        return (
            _uint(len(name), 4)
            + _uint(len(descriptor), 4)
            + _uint(0, 4)
            + name
            + b"\x00" * ((-len(name)) & 3)
            + descriptor
            + b"\x00" * ((-len(descriptor)) & 3)
        )

    contents = note(b"GNU", b"other") + note(b"NODE_SEA_BLOB", b"payload")
    entries = list(SeaBinary._elf_notes(contents, "little"))

    assert [entry[4].rstrip(b"\x00") for entry in entries] == [
        b"GNU",
        b"NODE_SEA_BLOB",
    ]
    assert entries[1][5] == b"payload"


def test_output_name_preserves_archive_suffix_and_blocks_traversal():
    assert _sanitize_output_name("copilot.tgz", "fallback") == "copilot.tgz"
    assert _sanitize_output_name("../../outside", "fallback") == ".._.._outside"
    assert _sanitize_output_name("..", "fallback") == "fallback"
